### ISSUE TITLE
A pull request

### ISSUE THREAD

**Issue by funderburkjim** [sanskrit-lexicon/rvlinks#2]
A user submitted various corrections via a pull request  (first time I've run into a pull request).
I got email of several links pertaining to this:

*  [pull request](https://github.com/sanskrit-lexicon/rvlinks/pull/1)
* https://patch-diff.githubusercontent.com/raw/sanskrit-lexicon/rvlinks/pull/1.diff

**Comment by funderburkjim** [comment]
On the pull request page is the comment:
```
    Elizarenkova - 08.103.14 corrected
    rearrange griffith stanzas

```
Also, there is a link:  `Files changed 55`.
and here are the names of the 55 files:
```
File Changes

    M rvhymns/rv08.049.html (43)
    M rvhymns/rv08.050.html (60)
    M rvhymns/rv08.051.html (54)
    M rvhymns/rv08.052.html (60)
    M rvhymns/rv08.053.html (48)
    M rvhymns/rv08.054.html (48)
    M rvhymns/rv08.055.html (30)
    M rvhymns/rv08.056.html (31)
    M rvhymns/rv08.057.html (24)
    M rvhymns/rv08.058.html (18)
    M rvhymns/rv08.059.html (46)
    M rvhymns/rv08.060.html (105)
    M rvhymns/rv08.061.html (107)
    M rvhymns/rv08.062.html (70)
    M rvhymns/rv08.063.html (72)
    M rvhymns/rv08.064.html (71)
    M rvhymns/rv08.065.html (69)
    M rvhymns/rv08.066.html (81)
    M rvhymns/rv08.067.html (104)
    M rvhymns/rv08.068.html (93)
    M rvhymns/rv08.069.html (92)
    M rvhymns/rv08.070.html (78)
    M rvhymns/rv08.071.html (78)
    M rvhymns/rv08.072.html (90)
    M rvhymns/rv08.073.html (90)
    M rvhymns/rv08.074.html (78)
    M rvhymns/rv08.075.html (79)
    M rvhymns/rv08.076.html (60)
    M rvhymns/rv08.077.html (56)
    M rvhymns/rv08.078.html (54)
    M rvhymns/rv08.079.html (48)
    M rvhymns/rv08.080.html (55)
    M rvhymns/rv08.081.html (54)
    M rvhymns/rv08.082.html (54)
    M rvhymns/rv08.083.html (55)
    M rvhymns/rv08.084.html (54)
    M rvhymns/rv08.085.html (55)
    M rvhymns/rv08.086.html (32)
    M rvhymns/rv08.087.html (36)
    M rvhymns/rv08.088.html (39)
    M rvhymns/rv08.089.html (43)
    M rvhymns/rv08.090.html (35)
    M rvhymns/rv08.091.html (42)
    M rvhymns/rv08.092.html (162)
    M rvhymns/rv08.093.html (155)
    M rvhymns/rv08.094.html (67)
    M rvhymns/rv08.095.html (54)
    M rvhymns/rv08.096.html (101)
    M rvhymns/rv08.097.html (76)
    M rvhymns/rv08.098.html (62)
    M rvhymns/rv08.099.html (42)
    M rvhymns/rv08.100.html (58)
    M rvhymns/rv08.101.html (71)
    M rvhymns/rv08.102.html (93)
    M rvhymns/rv08.103.html (80)
```

**Comment by funderburkjim** [comment]
## rv08.049

@Haqob 

I'm trying to understand your pull request.   

In the list of file changes in the pull request, the first file is for [rv08.049](https://sanskrit-lexicon.github.io/rvlinks/rvhymns/rv08.049.html).

The first verse in the current version is:
```
rv08.049.01

अ॒भि प्र वः॑ सु॒राध॑स॒मिन्द्र॑मर्च॒ यथा॑ वि॒दे। यो ज॑रि॒तृभ्यो॑ म॒घवा॑ पुरू॒वसुः॑ स॒हस्रे॑णेव॒ शिक्ष॑ति॥

abhi pra vaḥ surādhasam indram arca yathā vide |
yo jaritṛbhyo maghavā purūvasuḥ sahasreṇeva śikṣati ||

Воспой, как полагается,
Вашего Индру, раздающего дары,
Который, будучи щедрым, обладая многим добром,
Словно тысячей, хочет помочь певцам.

Stimmt euer Lied auf den freigebigen Indra an, wie er bekannt ist, 
der wie ein schätzereicher Freigebiger mit tausend Kühen den 
Sängern gern zu Diensten steht.

AGNI, come hither with thy fires; we choose thee as Invoking Priest.
 Let the extended ladle full of oil balm thee, best Priest, to sit on sacred grass.
```

The pull request suggests changing the English translation to:
```
TO you will I sing Indra's praise who gives good gifts as well we know;
Let the extended ladle full of oil balm thee, best Priest, to sit on sacred grass.   
The praise of Maghavan who, rich in treasure, aids his singers with wealth thousandfold.
```

**Comment by funderburkjim** [comment]
## First comments on 08.049.01

* The Sanskrit and *current* English translation are clearly inconsistent 
   * No mention of agni in the Sanskrit, but agni mentioned in current English
* The Sanskrit and *proposed* English translation appear to be in sync.
* Also, the *proposed* English appears to be consistent with the current German and Russian

**Comment by funderburkjim** [comment]
## Second comments
HOWEVER,  I don't think the problem will be fixed by the pull request suggestion of replacing
the *current* English with the *proposed* English.

The reason is that the *current* English is the Griffith translation of 08.049.01.   My reference is
https://www.sacred-texts.com/hin/rigveda/rv08049.htm.

Similarly, the *proposed* English is the Griffith translation of 08.093.01 [reference](https://www.sacred-texts.com/hin/rigveda/rv08093.htm).


Further note that the current English for 08.093.01 is `TO you will I sing Indra's praise ...`,  which
appears correct for 08.093.01; but  our current Sanskrit, Russian, and German are for some
other verse.

**Comment by funderburkjim** [comment]
## Interim conclusion
There are problems with  the rvlinks verses -- 

The pull request  suggested does not solve those problems.

These problems need to be solved.

@Haqob and @gasyoun  -- please comment and help to get a solution.

**Comment by Haqob** [comment]
Dear @funderburkjim and @gasyoun 

I am a research assistant for the VedaWeb project (https://vedaweb.uni-koeln.de), which relies on your data for some of the displayable translations. Since the verses are incorrectly aligned in the Griffith translation, they are currently also being displayed incorrectly on the VedaWeb website. That is why @vocabulista suggested that I create this pull request, so that we can all profit from the improvement to the data. I apologize for not explaining earlier and in detail what I did exactly.

In my view, the pull request does solve the problem and I am going to explain why:

RV hyms 08.049-08.59 together form the apocryphal Vālakhilya (see https://en.wikipedia.org/wiki/Mandala_8), which is placed at the end of the eighth book by some authors, while others maintain the traditional numbering. Griffith has placed it at the end of his translation and numbered his translations accordingly. That is why his translation is out of sync with the others if we just align them simply based on the way each of the translators numbers the verses.

The translations should be assigned to verses based on the original Sanskrit text and how it is ordered in the data, any other way is impractical and makes no sense. Since the Sanskrit text is in the traditional order, the translations should also be adapted to that ordering, no matter in what order they appear in the original publications, and that is what I did.

Additionally, in every case where the number of verses per hymn does not match between two hymns given the same number by Griffith and the traditional order, there are either leftover verses with no English translation ("-en-" in the data) or part of the Griffith translation is cut off. This is also solved in the pull request by adding the data that was cut off directly from the Griffith book.

I should also point out that there seem to be some issues with the Russian translation as well, since in some places I stumbled upon empty verses with only "-ru-" where the Russian translation should go, but I have not yet followed up to find out why this is.

I hope this clarifies the issue.

**Comment by funderburkjim** [comment]
Yes, that helps.

Let me paraphrase to see if I've understood properly.

* The Griffith translation numbering is non-standard (in the places you identified in the pull request).
* The rvlinks verses in Devanagari are numbered in the traditional way.
   * I confirmed this by comparing  [Devanagari of rvlinks rv.08.049.01](https://sanskrit-lexicon.github.io/rvlinks/rvhymns/rv08.049.html) to https://aurobindo.ru/workings/matherials/rigveda/08/08-049.htm.

@Haqob  -- agree with paraphrase so far?

**Comment by Haqob** [comment]
Yes, that's correct.

**Comment by funderburkjim** [comment]
Further, the pull request moves the English translation from verses 08.93-103 to 08.49-59 .  Right?

Where do the new 08.060 to 08.103 come from ?

**Comment by funderburkjim** [comment]
@Haqob   What about 08.060 to 08.103?

**Comment by Haqob** [comment]
The new 08.060-08.103 are the old 08.49-08.92, which were positioned before the Valakhilya in the Griffith ordering but are now placed after it in accordance with the traditional order.

**Comment by gasyoun** [comment]
> Griffith has placed it at the end of his translation and numbered his translations accordingly. That is why his translation is out of sync with the others if we just align them simply based on the way each of the translators numbers the verses.

Now I start to understand.

> I should also point out that there seem to be some issues with the Russian translation as well, since in some places I stumbled upon empty verses with only "-ru-" where the Russian translation should go, but I have not yet followed up to find out why this is.

Yes, quite a few are still missing since 2013. And no comments. What to do with the lacking comments? In none language they are digitized.

**Comment by funderburkjim** [comment]
>  the new 08.060-08.103 are the old 08.49-08.92,

Good. That completes the story for me.

**Comment by funderburkjim** [comment]
Merge now perform (see [pull request](https://github.com/sanskrit-lexicon/rvlinks/pull/1)).

**Comment by funderburkjim** [comment]
@Haqob   Thanks for the work in finding and solving this problem!

**Comment by funderburkjim** [comment]
## Problem with duplicate English in rv.08.049

The merged pull has both old and new english translations in rv.08.049 at verse 5 and following.

For instance, at verse 6:
![image](https://user-images.githubusercontent.com/6393033/96646102-a0de1e00-12f9-11eb-8fe5-865ae3dcf688.png)

Also, removed tab characters in rv08.091.html.

These changes noticed by a python program to find missing translations.
